# Generated by Django 4.0.2 on 2025-12-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='youtube_is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
