# Generated by Django 4.0.2 on 2025-12-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_youtube_is_playing_room_youtube_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='youtube_is_playing',
        ),
        migrations.AlterField(
            model_name='room',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
