# Generated by Django 4.0.2 on 2026-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_coursenote'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursenote',
            name='rooms_cours_room_id_c014f5_idx',
        ),
        migrations.AlterField(
            model_name='room',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='coursenote',
            index=models.Index(fields=['room', 'timecode'], name='rooms_cours_room_id_d2c136_idx'),
        ),
    ]
