# Generated by Django 4.0.2 on 2026-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Professeur'), ('student', 'Étudiant')], default='student', max_length=20),
        ),
    ]
